#
#
# CREATE A COPY OF THIS FILE AND STORE THE LOCATION IN 
# THE ENVIRONMENT VARIABLE XERO_TEST_CONFIG TO ENABLE
# WHEN PERFORMING A 'make test'
#
# THIS ENV WILL ALSO WORK FOR COMMAND LINE WHERE VALUES
# ARE NOT PASSED INTO THE CONSTRUCTOR
#
# See README and 'perldoc Xero' for more detail
#

[PRIVATE_APPLICATION]
CONSUMER_KEY    = YOUR_OAUTH_CONSUMER_KEY, 
CONSUMER_SECRET = YOUR_OAUTH_CONSUMER_SECRET, 
KEYFILE         = /path/to/privatekey.pem

[PUBLIC_APPLICATION]
# NAME            = 
# CONSUMER_KEY    = 
# CONSUMER_SECRET = 


[PARTNER_APPLICATION]
# NOT IMPLEMENTED YET